services:

  websitesa-helpers-yii2:
    build: .
    container_name: websitesa-helpers-yii2
    volumes:
      - ./:/app
      - $HOME/.ssh:/root/.ssh
      - /var/.envs/.env:/var/.envs/.env
    env_file:
      - /var/.envs/.env
    cpus: 0.3
    mem_limit: 512m
