services:

  websitesa-helpers-yii2:
    build:
      context: .
      args:
        PHP_BASE_IMAGE_VERSION: 8.3-apache
    container_name: websitesa-helpers-yii2
    volumes:
      - ./:/app
      - $HOME/.ssh:/root/.ssh
      - /var/.envs/.env:/var/.envs/.env
    env_file:
      - /var/.envs/.env
    cpus: 0.3
    mem_limit: 512m
